### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by vikas5914** [vikas5914/woo-atom-payment-gateway#1]
Need help to write better Readme

**Comment by yatingupta10** [comment]
Have to make the text more readable?
convert it into proper Markdown format?

**Comment by FleetAdmiral** [comment]
Could you elaborate on the issue you want solved? As in in which way you'd like the README to be enhanced so that i could work on it? Or i should make changes as i see fit?

**Comment by momja** [comment]
You can use # to make headers in markdown format, and a bunch of other cool things. Check out this cool link for help with md format: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by yatingupta10** [comment]
yes you can use # for headings and refer to Markdown cheatsheet!

**Comment by FleetAdmiral** [comment]
Cool, onto it 👍
