### ISSUE TITLE
Call to undefined function xml_parser_create()

### ISSUE THREAD

**Issue by devevignesh** [vikas5914/woo-atom-payment-gateway#6]
During checkout getting the following error:

CRITICAL Uncaught Error: Call to undefined function xml_parser_create() in /var/www/html/wp-content/plugins/woo-atom-payment-gateway/class-wc-gateway-atom.php:245

in this line https://github.com/vikas5914/woo-atom-payment-gateway/blob/master/class-wc-gateway-atom.php#L244

WordPress Version - 5.0.4
Woocommerce Version - 3.5.3

**Comment by vikas5914** [comment]
Hi @devevignesh 

You have to install PHP XML extension in your server.

**Comment by vignesh-effone** [comment]
Hey @vikas5914

Thanks for your response. I can see `xml` installed in aws by doing `php -m`. It seems like there is some [dependencies](https://forums.aws.amazon.com/thread.jspa?threadID=275613), let me try to fix that. If you find anything for me, please update the same in comment.   

PHP --v 7.2

**Comment by devevignesh** [comment]
Hey @vikas5914

Thanks for your response. I can see xml installed in aws by doing php -m. It seems like there is some [dependencies](https://forums.aws.amazon.com/thread.jspa?threadID=275613), let me try to fix that. If you find anything for me, please update the same in comment.

PHP --v 7.2

**Comment by devevignesh** [comment]
Fixed by reinstalling php version.
